
export const ADD_RECIPE = "ADD_RECIPE"
export const START_LOADING_RECIPES = "START_LOADING_RECIPES";
export const SUCCESSFULLY_LOADED_RECIPES = "SUCCESSFULLY_LOADED_RECIPES";
export const FAILED_LOADING_RECIPES = "FAILED_LOADING_RECIPES";

export const ADD_CUISINE = "ADD_CUISINE"
export const START_LOADING_CUISINES = "START_LOADING_CUISINES";
export const SUCCESSFULLY_LOADED_CUISINES = "SUCCESSFULLY_LOADED_CUISINES";
export const FAILED_LOADING_CUISINES = "FAILED_LOADING_CUISINES"