export const ADD_CUISINE = "ADD_CUISINE"
export const START_LOADING_CUISINES = "START_LOADING_CUISINES";
export const SUCCESSFULLY_LOADED_CUISINES = "SUCCESSFULLY_LOADED_CUISINES";
export const FAILED_LOADING_CUISINES = "FAILED_LOADING_CUISINES"